.github/workflows/integrate.yaml
.github/workflows/on_pull_request.yaml
.github/workflows/on_push.yaml
.github/workflows/publish.yaml
.github/workflows/release.yaml
lib/charms/grafana_k8s/v0/grafana_dashboard.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py

Charming actions updated according to the ones agreed on template-operator charm.
The aim was to:
- update release charm action
- have two publish actions for `on: push` and `on: pull_request`:
- on pull_request, publish to branch no matter if tests passed (tests and publish should run simultaneously)
- on push, publish to latest/edge only if tests passed
- avoid re-running the tests on pull_request
- use reusable workflows in order to avoid duplication of code.
Note: this is a single-charm repo with one resource.

Add charming actions

---

.github/workflows/integrate.yaml
metadata.yaml
requirements-integration.in
requirements-integration.txt
src/charm.py
tests/integration/test_charm.py
tests/unit/test_charm.py

- Introduce ingress relation so that a virtualService can be created pointing to the envoy's service and UI components can access it using the [gRPC-Web](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/grpc_web_filter) protocol.
- Add ingress relation unit and integration test
Fixes #61

feat: Introduce ingress relation

---

metadata.yaml
src/charm.py
tests/unit/many_relations.yaml

Details in #63.
- Update envoy configuration to:
- include empty value for [static.resources.http2_protocol_options](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/upstreams/http/v3/http_protocol_options.proto#extensions-upstreams-http-v3-httpprotocoloptions-explicithttpconfig) field since this must be set.
- revert [max_grpc_timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html#envoy-v3-api-field-config-route-v3-routeaction-max-grpc-timeout) to 60 (a large enough timeout). Setting it to 0 resulted in the SDK not 
rendering it. When this value is empty, envoy uses [timeout](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto.html#envoy-v3-api-field-config-route-v3-routeaction-timeout)'s …

fix: Update envoy configuration

---

metadata.yaml
src/charm.py

* Rename relation from `grafana-dashboards` to `grafana-dashboard` in order to:
* follow what every other CKF charm does (examples: [minio](https://github.com/canonical/minio-operator/blob/061c09d70d7474b349cf8e2df9642eab780c4729/metadata.yaml#L50), [seldon](https://github.com/canonical/seldon-core-operator/blob/d58d13249f6aa9e5e651df7754ba3258c6603cc5/metadata.yaml#L32))
* not diverge from the [grafana library default](https://github.com/canonical/envoy-operator/blob/338f000c2c2e879be478ccbcbf555242542b5874/lib/charms/grafana_k8s/v0/grafana_dashboard.py#L51).
Part of canonical/bundle-kubeflow#856
Refs canonical/bundle-kubeflow#834

fix: Rename relation to `grafana-dashboard`

---

src/grafana_dashboards/envoy-service.json.tmpl

* Add `ckf` tag to the grafana dashboard.
* Fix dashboard panels not working by: 
* Replacing unavailable metrics with available ones
* Adding 2 minutes instead of 1 in places where rate() is used since
this requires more than one scrape data points.
* Remove rate() from panels that shows percentages.
* Remove labels where the metrics don't provide them.
Part of canonical/bundle-kubeflow#856
Refs canonical/bundle-kubeflow#834
Closes #73

fix: Fix dashboard panels not working

---

src/grafana_dashboards/envoy-service.json.tmpl

Backport the following:
* Add `ckf` tag to the grafana dashboard.
* Fix dashboard panels not working by: 
* Replacing unavailable metrics with available ones
* Adding 2 minutes instead of 1 in places where rate() is used since this requires more than one scrape data points.
* Remove rate() from panels that shows percentages.
* Remove labels where the metrics don't provide them.
Part of canonical/bundle-kubeflow#856
Ref canonical/bundle-kubeflow#834
Ref #73

backport(fix): Fix dashboard panels not working from #80

---

metadata.yaml
src/charm.py

Backport the following:
* Rename relation from `grafana-dashboards` to `grafana-dashboard` in order to:
* follow what every other CKF charm does.
* not diverge from the grafana library default.
Part of canonical/bundle-kubeflow#856
Refs canonical/bundle-kubeflow#834

backport(fix): Rename relation to `grafana-dashboard` from #79

---

charmcraft.yaml
lib/charms/mlops_libs/v0/k8s_service_info.py
metadata.yaml
requirements-unit.txt
requirements.in
requirements.txt
src/charm.py
src/components/k8s_service_info_component.py
src/components/k8s_service_info_requirer_component.py
tests/integration/test_charm.py
tests/unit/test_charm.py

Use the k8s_service_info for receiving the MLMD GRPC Service info instead of using the SDI, as it will stop being supported soon.
Fixes #76
NOTE for reviewers:
* I have added a component for wrapping the k8s service info requirer because we need to:
1. Have a way to return a status based on the relation conditions
2. Because there is no other way to do logic that prevents errors in the init method of the charm. For instance, it would be weird to have a try/catch in the init method for ensuring the required relation is established.
* Also note that this component could be placed in chisme, BUT that requires us to put charm libraries in the package, which is under discussion by the team.
1. Deploy the charm in this branch
2. Deploy `mlmd` from `channel latest/edge` with `trust`
3. Relate …

refactor: use k8s_service_info lib instead of SDI

---

lib/charms/prometheus_k8s/v0/prometheus_scrape.py
requirements.in

Ref canonical/bundle-kubeflow#880

chore: Bump prometheus_scrape lib

---

tools/get-images.sh

cherry-picks eacf315c26b79d83bc3b04f961ef12f525e0c2d1 to `track/2.0`

feat: add get images script (#96)

---

metadata.yaml

closes #98 
Adds the definition for the schemas of:
* `grpc` relation
* `grpc-web` relation
to the metadata.yaml instead of used a remote link to enable deploying `envoy` in airgapped environments.

fix: define relations schema in metadata.yaml to enable airgapped

---

CONTRIBUTING.md
metadata.yaml
src/templates/envoy.yaml.j2
tests/integration/test_charm.py

* Update manifests and envoy configuration
* Add CONTRIBUTING.md file with instructions for updating manifests
I document in detail in #106 the situation with integration tests but summary is that envoy is functional and KFP pipeline steps can get the artifacts while curling envoy with the same headers fails. I filed an issue so we can work on envoy integration tests separately, since we need to spend more time on understanding envoy - kfp-ui relation and imitate this in our tests. I 've already done some exploration but did not want to spend more time here, since this has already been overdue and I would not want to introduce a test that I do not understand. Instructions for manual testing are below.  
1. Deploy CKF from latest/edge using juju agent 3.5.0 due to …

chore: bump manifests 2.0.3 -> 2.2.0

---

lib/charms/loki_k8s/v1/loki_push_api.py
metadata.yaml
requirements-integration.in
requirements-integration.txt
requirements-unit.txt
requirements.txt
src/charm.py
tests/integration/test_charm.py
tests/unit/test_charm.py

Added logging relation and cos integration tests from chisme.
fixes: #104
How I tested it:
from terminal
```bash
$ tox -e integration -- --keep-models
$ juju switch test-charm-2ar5
$ juju consume u1-k8s:cos.loki-logging
Added u1-k8s:admin/cos.loki-logging as loki-logging
$ juju integrate loki-logging grafana-agent-k8s
$ kubectl logs -n test-charm-2ar5 envoy-0 --container envoy --tail 100 | grep '\[envoy\]'
2024-06-17T16:54:31.699Z [envoy] [2024-06-17 16:54:31.699][15][info][main] [source/server/server.cc:417]   envoy.compression.compressor: envoy.compression.brotli.compressor, envoy.compression.gzip.compressor, envoy.compression.zstd.compressor
2024-06-17T16:54:31.699Z [envoy] [2024-06-17 16:54:31.699][15][info][main] [source/server/server.cc:417]   envoy.matching.http.input: …
```

Add logging relation envoy

---

.github/workflows/integrate.yaml

Part of canonical/bundle-kubeflow#944

ci: use juju 3.4/stable instead of 3.5/stable in track 2.0

---

src/charm.py

Adds the condition from integration tests as a `livenessProbe` to the workload container in order to ensure that the workload container restarts if it's not functional.
Closes canonical/bundle-kubeflow#966

fix: Add livenessProbe to workload pod

---

.github/workflows/publish.yaml

Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993

ci(upload-charm): use charmcraft from latest/candidate in track/2.2

---

.github/workflows/integrate.yaml
.gitignore
terraform/README.md
terraform/main.tf
terraform/outputs.tf
terraform/variables.tf
terraform/versions.tf
tox.ini

Ref: #131 
This PR creates a `terraform/` directory that hosts the Terraform module for this charm. It follows the structure proposed in [this spec](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit).
To test the module:
- Clone the repository and switch to this branch.
- First run `tox -e tflint` to ensure that linting is correct.
- Run `terraform apply -var "channel=latest/edge" -var "model_name=kubeflow" --auto-approve` and wait until the charm is `Active` and `Idle`.

Add Terraform module

---

metadata.yaml

Upgrade manifests and images to 2.4 according to KFP's manifests. 
See kfp's [CONTRIBUTING.md](https://github.com/canonical/kfp-operators/blob/main/CONTRIBUTING.md) file for instructions.
Close https://warthogs.atlassian.net/browse/KF-6862

chore: upgrade to 2.4.0

---

metadata.yaml
src/components/pebble.py

Closes #149 
* Integrates Canonical envoy rock version `1.28.2` from https://github.com/canonical/envoy-rock
* Adjusts the entrypoint command to work with the rock
1. Deploy `latest/edge` bundle on juju 3.6 and microk8s 1.31
2. Refresh the envoy charm and set the image to the rock:
```
juju refresh envoy --channel=latest/edge/pr-150 --base ubuntu@20.04 --resource oci-image=ghcr.io/canonical/envoy:1.28.2
```
3. Run the kfp-v2 [UATs](https://github.com/canonical/charmed-kubeflow-uats?tab=readme-ov-file#run-the-tests) and make sure the pipeline succeeds.
Results:
UATs passed and pipeline run succeeded

chore: integrate envoy rock

---

.github/workflows/integrate.yaml
concierge.yaml

Ref: https://github.com/canonical/bundle-kubeflow/issues/1334
This PR backports the update to use Canonical K8s in our integration tests. Note that we also backport a fix to use `24.04` as base in the `release-charm` action.

(backport): Update CI to use Canonical K8s

---

.github/workflows/integrate.yaml

Ref: https://github.com/canonical/bundle-kubeflow/issues/1341
This PR backports a change to only run the `dump-charm-debug-artifacts` action on failure in order to save time.

fix: Change dump-charm-debug-artifacts on failure
